#On AWS the yml file has the following instead of build
#image: rotto32/bowsers-castle-booking-mod:express_server

version: "3"
services:
  server:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3004:3004'

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: H4d3s
