version: "3"

services:
  server:
    image: rotto32/bowsers-castle-booking-mod:express_server
    depends_on:
      - 'database'
    ports:
      - '3004:3004'

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ----
